export const AGENT_ACTIONS = {
  SET_YEAR: "set_year",
  COMPARE: "compare",
  SELECT_ENTITY: "select_entity",
  SHOW_EVENT: "show_event",
  SHOW_PERSON: "show_person",
  SHOW_SOURCES: "show_sources",
  START_LESSON: "start_lesson",
  SHOW_CHANGE: "show_change",
  START_STORY: "start_story",
  OPEN_COMPARISON: "open_comparison",
  TOGGLE_LAYER: "toggle_layer",
  SELECT_ROUTE: "select_route",
  START_ROUTE_JOURNEY: "start_route_journey",
  SELECT_PLACE: "select_place",
  SHOW_GEOGRAPHY: "show_geography",
  START_GEOGRAPHY_STORY: "start_geography_story",
  SHOW_EVIDENCE: "show_evidence",
  SHOW_ARCHIVE_MAPS: "show_archive_maps",
  SELECT_ARCHIVE_MAP: "select_archive_map",
  START_ARCHIVE_COMPARISON: "start_archive_comparison",
  SHOW_REVIEW_QUEUE: "show_review_queue",
  SHOW_DISPUTE: "show_dispute",
  START_EVIDENCE_STORY: "start_evidence_story",
  EXPORT_CITATION: "export_citation",
  RESET: "reset",
};
